In [11]:
import numpy as np
myarr = np.array([0,0,0,10,22,3,2,33,22,12,10,11,20,11,20,22,20,0,23])
myarr.sort()
unique_values = np.unique(myarr)
print(unique_values)


[ 0  2  3 10 11 12 20 22 23 33]


In [34]:
unique_values,counts = np.unique(myarr,return_counts=True)
dict_ = dict(zip(unique_values,counts))
print(dict_)
print(np.asarray((unique_values,counts)))

{0: 4, 2: 1, 3: 1, 10: 2, 11: 2, 12: 1, 20: 3, 22: 3, 23: 1, 33: 1}
[[ 0  2  3 10 11 12 20 22 23 33]
 [ 4  1  1  2  2  1  3  3  1  1]]


In [36]:
print(np.asarray((unique_values,counts)).T)

[[ 0  4]
 [ 2  1]
 [ 3  1]
 [10  2]
 [11  2]
 [12  1]
 [20  3]
 [22  3]
 [23  1]
 [33  1]]


In [20]:
#convert two equal size array to dictionary
fruits = np.array(["Mango","Grapes","Orange"])
prices = np.array([30,100,230])

combine = dict(zip(fruits,prices))
print(combine)


{'Mango': 30, 'Grapes': 100, 'Orange': 230}


In [24]:
#convert numarray fruits and prices
result = np.asarray((fruits,prices))
print(result)

[['Mango' 'Grapes' 'Orange']
 ['30' '100' '230']]
