In [112]:
import numpy as np
myarray = np.array([1,2,3])
print(myarray)

[1 2 3]


In [113]:
type(myarray)

numpy.ndarray

In [114]:
_2d_array = np.array([[22,30,232,33],[22,12,12,22]])
_2d_array.ndim

2

In [115]:
print(_2d_array)

[[ 22  30 232  33]
 [ 22  12  12  22]]


In [116]:
#get the size of array using size 
print(_2d_array.size)

8


In [117]:
#get total rows and column of array using shape 
_2d_array.shape  #(rows,column)


(2, 4)

In [118]:
#get the datatype of array using dtype
_2d_array.dtype

dtype('int32')

In [119]:
#3d array
arr =  np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [3, 5, 6]
    ], 
    [
        [7, 8, 6],
        [10, 11, 6],
        [10, 11, 6],
        [10, 11, 6],
        [10, 11, 6]
    ],
    [
        [7, 8, 6],
        [10, 11, 6],
        [10, 11, 6],
        [10, 11, 6],
        [10, 11, 6]
    ],
    [
        [7, 8, 6],
        [10, 11, 6],
        [10, 11, 6],
        [10, 11, 6],
        [10, 11, 6],
        
        
        
    ]
])
# print(arr.ndim)
# srch = np.where(arr==6)
# print(srch)

In [120]:
# print(arr[0,1,2])
# print(arr[1,0,2])
# print(arr[1,1,2])

In [121]:
# print(arr[0,0])


In [122]:
# print(arr)

In [123]:
print("Number of element :",arr.size)

Number of element : 60


In [124]:
print("Shape :",arr.shape)
#Rows, number of arrays, Columns

Shape : (4, 5, 3)


In [125]:
# arr[0,4] =0,0,0
# print(arr)
print(arr[0,4])

[3 5 6]


In [126]:
shape = arr.shape
total_rows=shape[0]
width = shape[1]
print(width)
print(arr[0,4])


5
[3 5 6]


In [127]:
s = np.array([7,8,6])
th = np.array([3,5,6])
for row in range(total_rows):
      for a in range(width):
          # print(f"row:{row} column:{a}")
          print(arr[row,a])
          check_ = np.array_equal(arr[row,a],s) or np.array_equal(arr[row,a],th)
          if not check_:
              arr[row,a]=0,0,0
          





[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[3 5 6]
[7 8 6]
[10 11  6]
[10 11  6]
[10 11  6]
[10 11  6]
[7 8 6]
[10 11  6]
[10 11  6]
[10 11  6]
[10 11  6]
[7 8 6]
[10 11  6]
[10 11  6]
[10 11  6]
[10 11  6]


In [128]:
print(arr)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [3 5 6]]

 [[7 8 6]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[7 8 6]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[7 8 6]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [129]:
#compare array
a = np.array([0,255,0])
b = np.array([0,255,0])
c=np.array([0,0,0])
result = np.array_equal(a,b) or np.array_equal(a,c)
print(result)


True
