In [4]:
import numpy as np
mt = np.array([[1,2,3],[22,33,22],[0,0,10]])
print(mt)

[[ 1  2  3]
 [22 33 22]
 [ 0  0 10]]


In [7]:
mt.ndim

2

In [8]:
mt.shape

(3, 3)

In [9]:
mt.size

9

In [15]:
#use ones
my = np.ones(4)
print(my)

[1. 1. 1. 1.]


In [23]:
my = np.ones((3,4))
print(my)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
my.dtype

dtype('float64')

In [38]:
my = np.ones((2,2),int)
print(my)

[[1 1]
 [1 1]]


In [42]:
#0 matrics
zero = np.zeros((3,5),int)
print(zero)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [77]:
#emtpy array using empty

In [78]:

em_arr = np.empty((2,4),int)
print(em_arr)

[[         0 1072693248          0 1072693248]
 [         0 1072693248          0 1072693248]]
