In [2]:
import numpy as np


In [3]:
#use arrange 
my_arr1 = np.arange(1,13)
print(my_arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
my_arr = np.arange(0,100,5,int)
print(my_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [32]:
#linspace
line_space = np.linspace(1,10,10, True,False,int)
print(line_space)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
#reshape()
mynew_arr = my_arr1.reshape(3,4)
print(mynew_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
re = mynew_arr.reshape(6,2)
print(re)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [8]:
#ravel() 
rl = mynew_arr.ravel()
print(rl)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
#flatten()
fltn = mynew_arr.flatten()
print(fltn)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
fltn = mynew_arr.flatten(order='F')
print(fltn)

[ 1  5  9  2  6 10  3  7 11  4  8 12]


In [11]:
#transpose()
tr = re.transpose() #(6,2) ==>(2,6)
print(tr)

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [25]:
#reshape more examles
r = np.array([2,3,45,5])
result = np.array([3.]).reshape(-1,1)
print(result)

[[  3.46]
 [300.  ]]
