In [143]:
import numpy as np
a = np.array([
    [
        [10,20,0],
        [10,20,0],
        [1,1,1],
        [0,0,0],
        [255,255,255]
    ],
     [
        [10,20,0],
        [10,20,0],
        [1,1,1],
        [0,0,0],
        [255,255,255]
    ],
     [
        [10,20,0],
        [10,20,0],
        [1,1,1],
        [0,0,0],
        [255,255,255]
    ],
     [
        [10,20,0],
        [10,20,0],
        [1,1,1],
        [0,0,0],
        [255,255,255]
    ],
])


In [144]:
print(a.size)

60


In [145]:
rows = a.shape[0]
columns = a.shape[1]

In [146]:
_arr =np.empty(3,int)
for row in range(rows):
    for column in range(columns):
        _check = np.array_equal(a[row,column],[255,255,255])
        if not _check:
           np.delete(a,a[row,column])
            
    
        
    

In [147]:
print(a)

[[[ 10  20   0]
  [ 10  20   0]
  [  1   1   1]
  [  0   0   0]
  [255 255 255]]

 [[ 10  20   0]
  [ 10  20   0]
  [  1   1   1]
  [  0   0   0]
  [255 255 255]]

 [[ 10  20   0]
  [ 10  20   0]
  [  1   1   1]
  [  0   0   0]
  [255 255 255]]

 [[ 10  20   0]
  [ 10  20   0]
  [  1   1   1]
  [  0   0   0]
  [255 255 255]]]


In [148]:
l =np.empty(0,int)
b = np.array([2,3,4])
l = np.append(l,b)

print(l)

[2 3 4]
